# Generated by Django 5.2.7 on 2025-11-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='categories',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='category',
            field=models.CharField(default='technology', max_length=50),
        ),
    ]
