# Generated by Django 5.2.7 on 2025-11-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_remove_userpreference_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='category',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='categories',
            field=models.TextField(default='technology'),
        ),
    ]
